const Arrays := preload("Arrays.gd")
const BitMasks := preload("BitMasks.gd")
const Files := preload("Files.gd")
const Nodes := preload("Nodes.gd")
const PropertyInfo := preload("PropertyInfo.gd")
const Scripts := preload("Scripts.gd")
const Strings := preload("Strings.gd")
const Settings := preload("Settings.gd")
const Signals := preload("Signals.gd")
const Timers := preload("Timing.gd")
const Tweens := preload("Tweens.gd")
const Variants := preload("Variants.gd")
const Vectors := preload("Vectors.gd")

## Static class
func _init() -> void: assert(false, "Class can't be instantiated")