# Generated by Namespacer - (<github link>)
class_name RootNS

const SubNS := preload("uid://dxsr56c4a4r73") # res://test/RootNS/SubNS/_index.gd
const something := preload("uid://cvl5yl1aqd86") # res://test/RootNS/something.gd
