# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const EditorThemeExplorerList := preload("uid://dg4oc6ix73l6v")
const EditorThemeTypeListPicker := preload("uid://bdiy7eqm1bnty")
const EditorThemeStyleBoxList := preload("uid://da2vp20fitmmd")
const EditorThemeIconList := preload("uid://dg52ydkn8cb5v")
const EditorThemeColorList := preload("uid://ba2l7d86y8dr6")

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

