# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const EditorPropertyCustomArray := preload("uid://b1lj0kn0acpb") # res://addons/o2/src/EditorExtensions/EditorPropertyCustomArray.gd
const EditorInspectorContextMenu := preload("uid://drhs82tyfy2j2") # res://addons/o2/src/EditorExtensions/EditorInspectorContextMenu.gd

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

