# Generated by Namespacer - (<github link>)

const EditorPropertyCustomArray := preload("uid://b1lj0kn0acpb") # res://addons/o2/src/EditorExtensions/EditorPropertyCustomArray.gd
const EditorInspectorContextMenu := preload("uid://drhs82tyfy2j2") # res://addons/o2/src/EditorExtensions/EditorInspectorContextMenu.gd
