# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const EditorPropertyCustomArray := preload("uid://b1lj0kn0acpb")
const EditorInspectorContextMenu := preload("uid://drhs82tyfy2j2")
const Controls := preload("uid://fyqh5efaxlsl")

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

