# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const Settings := preload("uid://bnlgkreosb7f1") # res://addons/o2/src/H/Editor/Settings.gd
const ArrayGroupHelper := preload("uid://bohxaq4g6c0ge") # res://addons/o2/src/H/Editor/ArrayGroupHelper.gd
const InspectorPlugin := preload("uid://bnnhvj75a5tfv") # res://addons/o2/src/H/Editor/InspectorPlugin.gd
const Theming := preload("uid://bfuxnqsle846q") # res://addons/o2/src/H/Editor/Theming.gd
const Plugins := preload("uid://cf3suapig37p6") # res://addons/o2/src/H/Editor/Plugins.gd
const SceneRootChangeNotifier := preload("uid://q222j6y6bix6") # res://addons/o2/src/H/Editor/SceneRootChangeNotifier.gd

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

