# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const EditorThemeExplorerList := preload("uid://dg4oc6ix73l6v")
const EditorThemeIconFlowContainer := preload("uid://dg52ydkn8cb5v")
const EditorThemeTypeListPicker := preload("uid://bdiy7eqm1bnty")
const EditorThemeStyleBoxList := preload("uid://da2vp20fitmmd")

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

