# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const DragAndDropPaletteList := preload("uid://cgmkhgex28eyb")
const EditorThemeExplorerList := preload("uid://dg4oc6ix73l6v")
const EditorThemeIconFlowContainer := preload("uid://dg52ydkn8cb5v")
const EditorThemeTypeListPicker := preload("uid://bdiy7eqm1bnty")
const EditorThemeStyleBoxList := preload("uid://da2vp20fitmmd")
const EditorIconButton := preload("uid://83yq2e5cupld")

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

