# Generated by Namespacer - (https://github.com/Tattomoosa/o2)
class_name H

const Settings := preload("uid://c6e5johjrra8m") # res://addons/o2/src/H/Settings.gd
const Timing := preload("uid://b4ta67gbaal3v") # res://addons/o2/src/H/Timing.gd
const Tweens := preload("uid://dkf5yxf66guok") # res://addons/o2/src/H/Tweens.gd
const Strings := preload("uid://c4tmrampbhsnv") # res://addons/o2/src/H/Strings.gd
const Colors := preload("uid://r8ihtiuvnq57") # res://addons/o2/src/H/Colors.gd
const Scripts := preload("uid://ccrljmm854ymp") # res://addons/o2/src/H/Scripts.gd
const Nodes := preload("uid://bhl4ujj8d255s") # res://addons/o2/src/H/Nodes.gd
const Metadata := preload("uid://crfj3m7c8x7ww") # res://addons/o2/src/H/Metadata.gd
const Variants := preload("uid://wyhrcrfkkryb") # res://addons/o2/src/H/Variants.gd
const PropertyInfo := preload("uid://0y6dd2sdx663") # res://addons/o2/src/H/PropertyInfo.gd
const Vectors := preload("uid://cj1jqwlms8gq2") # res://addons/o2/src/H/Vectors.gd
const Arrays := preload("uid://b5vdnyp8omjbx") # res://addons/o2/src/H/Arrays.gd
const Files := preload("uid://bv4oowk3jtdfd") # res://addons/o2/src/H/Files.gd
const Controls := preload("uid://cwgfxhurw1cls") # res://addons/o2/src/H/Controls.gd
const Signals := preload("uid://dy6ip7pa4g5bo") # res://addons/o2/src/H/Signals.gd
const Bools := preload("uid://ckewt6vl0aaf6") # res://addons/o2/src/H/Bools.gd
const Callables := preload("uid://cauu1bktrfieu") # res://addons/o2/src/H/Callables.gd
const BitMasks := preload("uid://cdxyctt6vtsa4") # res://addons/o2/src/H/BitMasks.gd
const Editor := preload("uid://bahjnk3m5dt1f") # res://addons/o2/src/H/Editor/_index.gd

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

