# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const ArrayGroupHelper := preload("uid://bohxaq4g6c0ge")
const InspectorPlugin := preload("uid://bnnhvj75a5tfv")
const IconGrabber := preload("uid://cuegmprm6qscr")
const Plugins := preload("uid://cf3suapig37p6")
const Settings := preload("uid://bnlgkreosb7f1")
const SceneRootChangeNotifier := preload("uid://q222j6y6bix6")

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

