# Generated by Namespacer - (https://github.com/Tattomoosa/o2)
class_name H

const Arrays := preload("uid://b5vdnyp8omjbx")
const BitMasks := preload("uid://cdxyctt6vtsa4")
const Bools := preload("uid://ckewt6vl0aaf6")
const Colors := preload("uid://r8ihtiuvnq57")
const Controls := preload("uid://cwgfxhurw1cls")
const Callables := preload("uid://cauu1bktrfieu")
const Files := preload("uid://bv4oowk3jtdfd")
const Metadata := preload("uid://crfj3m7c8x7ww")
const Nodes := preload("uid://bhl4ujj8d255s")
const PropertyInfo := preload("uid://0y6dd2sdx663")
const Strings := preload("uid://c4tmrampbhsnv")
const Scripts := preload("uid://ccrljmm854ymp")
const Signals := preload("uid://dy6ip7pa4g5bo")
const Settings := preload("uid://c6e5johjrra8m")
const Tweens := preload("uid://dkf5yxf66guok")
const Timing := preload("uid://b4ta67gbaal3v")
const Variants := preload("uid://wyhrcrfkkryb")
const Vectors := preload("uid://cj1jqwlms8gq2")
const Editor := preload("uid://bahjnk3m5dt1f")

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

