# Generated by Namespacer - (https://github.com/Tattomoosa/o2)

const FuzzySearch := preload("uid://1bkr3qluf8u5")

## "Static" class
func _init() -> void: assert(false, "Namespace class can't be instantiated")

